[package]
name = "stwo_wrapper"
version = "0.1.0"
edition = "2024_07"

[executable]

[dependencies]
cairo_execute = "2.12"
stwo_cairo_air = { git = "https://github.com/Ztarknet-recursion/stwo-cairo-fork", default-features = false, features = ["qm31_opcode", "blake_outputs_packing"] }

[cairo]
enable-gas = false