[workspace]
members = [
        "zebra-prove",
]

# Use the edition 2021 dependency resolver in the workspace, to match the crates
resolver = "2"

# `cargo release` settings

[workspace.metadata.release]

# We always do releases from the main branch
allow-branch = ["main"]

# Compilation settings

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Speed up release builds and sync tests using link-time optimization.
# Some of Zebra's code is CPU-intensive, and needs extra optimizations for peak performance.
#
# TODO:
# - add "-Clinker-plugin-lto" in .cargo/config.toml to speed up release builds
#     - add "-Clinker=clang -Clink-arg=-fuse-ld=lld" in .cargo/config.toml
# - also use LTO on C/C++ code:
#     - use clang to compile all C/C++ code
#     - add "-flto=thin" to all C/C++ code builds
#     - see https://doc.rust-lang.org/rustc/linker-plugin-lto.html#cc-code-as-a-dependency-in-rust
lto = "thin"


[workspace.lints.rust]
# The linter should ignore these expected config flags/values
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(tokio_unstable)', # Used by tokio-console
    'cfg(zcash_unstable, values("zfuture", "nu6.1", "nu7"))' # Used in Zebra and librustzcash
] }